### ISSUE TITLE
Clarify/Add Gnome supported versions in README.

### ISSUE THREAD

**Issue by jayarc** [stanford-oval/almond-gnome#49]
Hi there, excited to see this project. Would love to help in the future potentially. Right now it looks like only Gnome 3.32 specifically is supported. Could you comment on that to verify and also comment on if any other versions of Gnome could work. Trying the flathub installer on Debian Buster right now says 3.32 is required. I tried Debian experimental which is at 3.34 and tried to modify 3.32 references to 3.34 with no luck at build time there. My next step is to install Fedora somewhere with 3.32 to test but it would be nice to have something on my daily driver distro Debian. Any ideas? Thanks for doing this work!

**Comment by gcampax** [comment]
Hi, and thanks for the interest in the project!
GNOME 3.34 is indeed supported, as I'm personally using Almond on Fedora 31 right now.

If you're referring to the flatpak manifest, we have not switched to the 3.34 runtime because it was released recently, but we could switch if needed. I didn't see any feature that made the switch necessary so far.
For the shell extension, 3.32 or 3.34 there is not much difference, and I run with `disable-extension-version-validation` set to true, but it's probably ok to release an update that enables 3.34 explicitly.

**Comment by gcampax** [comment]
Closing as there was no follow up.
